# Generated by Django 3.1.3 on 2020-11-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201129_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='no_image.jpg', upload_to='media'),
        ),
    ]
