# Generated by Django 3.1.3 on 2020-11-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201129_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(0, 'Old'), (1, 'New')], default=1),
        ),
    ]
