# Generated by Django 3.1.3 on 2020-12-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201201_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ref_num',
            field=models.TextField(default=None),
        ),
    ]
