# Generated by Django 3.1.3 on 2020-12-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201201_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ref_num',
        ),
    ]
