# Generated by Django 3.1.3 on 2020-12-01 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_item_ref_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ref_num',
            field=models.BigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
