# Generated by Django 3.1.3 on 2020-12-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201201_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
        ),
    ]
