# Generated by Django 3.1.3 on 2020-12-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20201201_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
