# Generated by Django 3.1.3 on 2020-12-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20201201_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
